# Generated by Django 5.2.5 on 2025-08-29 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3')])),
                ('course', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MBA', 'MBA')], max_length=20)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('MECH', 'Mechanical Engineering'), ('ECE', 'Electronics & Communication'), ('CIVIL', 'Civil Engineering')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
